parameters:
  - name: DataFactoryResourceId
    type: string
  - name: ZoneType
    type: string
  - name: ArmTemplateExportPath
    type: string
  - name: ArmTemplatesADFArtifact 
    type: string 
  - name: ArmTemplateParametersADFArtifact
    type: string 


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'
 
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(Build.Repository.LocalPath)/' 
    verbose: true
  displayName: 'Install npm package'
 
# Validates all of the Data Factory resources in the repository. You'll get the same validation errors as when "Validate All" is selected.
# Enter the appropriate subscription and name for the source factory. Either of the "Validate" or "Validate and Generate ARM temmplate" options are required to perform validation. Running both is unnecessary.
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(Build.Repository.LocalPath)/' #replace with the package.json folder
    customCommand: 'run build validate $(Build.Repository.LocalPath)/DataFactory/adf-gittestcgro-uksouth-dev-01 ${{ parameters.DataFactoryResourceId }}'
  displayName: 'Validate'

# Validate and then generate the ARM template into the destination folder, which is the same as selecting "Publish" from the UX.
# The ARM template generated isn't published to the live version of the factory. Deployment should be done by using a CI/CD pipeline. 

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(Build.Repository.LocalPath)/' #replace with the package.json folder
    customCommand: 'run build export ${{ parameters.ArmTemplateExportPath }}  ${{ parameters.DataFactoryResourceId }} "ADFnpmGeneratedArmTemplate"'
#For using preview that allows you to only stop/ start triggers that are modified, please comment out the above line and uncomment the below line. Make sure the package.json contains the build-preview command. 
 #customCommand: 'run build-preview export $(Build.Repository.LocalPath) /subscriptions/222f1459-6ebd-4896-82ab-652d5f6883cf/resourceGroups/GartnerMQ2021/providers/Microsoft.DataFactory/factories/Dev-GartnerMQ2021-DataFactory "ArmTemplate"'
  displayName: 'Validate and Generate ARM template'


# Publish the Artifact to be used as a source for a release pipeline
- task: PublishPipelineArtifact@1
  inputs:
      targetPath: '$(Build.Repository.LocalPath)/ADFnpmGeneratedArmTemplate'
      artifact: '${{ parameters.ArmTemplatesADFArtifact }}'
      publishLocation: 'pipeline'

- task: PublishPipelineArtifact@1
  inputs:
      targetPath: '$(Build.Repository.LocalPath)/Infrastructure/Services/${{ parameters.ZoneType }}'
      artifact: '${{ parameters.ArmTemplateParametersADFArtifact }}'
      publishLocation: 'pipeline'