parameters:
  - name: FeatureFlag_SQL_StopIfDataLossCanOccur
    type: boolean
    default: true
  - name: FeatureFlag_SQL_DeployDWH
    type: boolean
    default: false


name: Pipeline-$(Build.DefinitionName)-$(Date:yyyyMMdd)$(Rev:.r)

pr: none
trigger: none

variables:
- template: ..\Variables\Variables-Global.yml

pool: 'Azure Pipelines'


stages:

- template: ..\Stages\Stage-Environment.yml
  parameters:
          ServiceConnection: ${{ variables.serviceConnection }}
          Environment: ${{ variables.ProdEnvironment }}
          Location: ${{ variables.Location }}
          FeatureFlag_SQL_StopIfDataLossCanOccur: ${{ parameters.FeatureFlag_SQL_StopIfDataLossCanOccur }}
          FeatureFlag_SQL_DeployDWH: ${{ parameters.FeatureFlag_SQL_DeployDWH }}

